/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Liz
 */
import HashTable.Articulo;
import HashTable.Global;
import HashTable.HashTable;
import HashTable.Lector;
import HashTable.Lista;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class BuscarAutor extends javax.swing.JFrame {

    /**
     * Creates new form BuscarAutor
     */
    Global global = new Global();

    public BuscarAutor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDatos();
    }
    
    public DefaultListModel getDatos(Lista titulos) {
        DefaultListModel modelo = new DefaultListModel();
        int position = titulos.getFirst();
        while (position != -1) {
            Articulo art = (Articulo) titulos.array[position].getData();
            modelo.addElement(art.getTitulo());
            position = titulos.array[position].getNext();
        }
        this.panelTitulos.setModel(modelo);
        return modelo;
    }

    public void setDatos() {
        Lista lista = Global.getListaAutores();
        int position = lista.getFirst();
        while (position != -1) {
            this.choice.add((String) lista.array[position].data);
            position = lista.array[position].getNext();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        choice = new java.awt.Choice();
        mostrar = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelTitulos = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        send1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(77, 97, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 190, -1));

        mostrar.setBackground(new java.awt.Color(173, 157, 136));
        mostrar.setFont(new java.awt.Font("Expo M", 0, 12)); // NOI18N
        mostrar.setForeground(new java.awt.Color(0, 0, 0));
        mostrar.setText("SOLICITAR DETALLES");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 30));

        send.setBackground(new java.awt.Color(173, 157, 136));
        send.setForeground(new java.awt.Color(0, 0, 0));
        send.setText("Enviar");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel1.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jScrollPane3.setViewportView(panelTitulos);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 370, 260));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Expo M", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BUSCAR POR AUTOR");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        send1.setBackground(new java.awt.Color(173, 157, 136));
        send1.setFont(new java.awt.Font("Expo M", 0, 10)); // NOI18N
        send1.setForeground(new java.awt.Color(0, 0, 0));
        send1.setText("Regresar al menu");
        send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send1ActionPerformed(evt);
            }
        });
        jPanel1.add(send1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 160, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Expo M", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Seleccione un articulo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Expo M", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Seleccione un autor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        HashTable tabla = Global.getTabla();
        Articulo art = tabla.buscar(this.panelTitulos.getSelectedValue());
        String[] palabrasclave = art.getPalabrasClave();

        String txt = "" + art.getTitulo() + "\n"
                + "Autores:\n";

        for (int i = 0; i < art.getAutores().length; i++) {
            txt = txt + art.getAutores()[i]+ "\n";
        }
       txt = txt +"Palabras clave: " ;
       
        for (int i = 0; i < art.getPalabrasClave().length; i++) {
            txt = txt + art.getPalabrasClave()[i] + ", ";
        }
       
        JOptionPane.showMessageDialog(null,txt);
    }//GEN-LAST:event_mostrarActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        var tabla = global.getTabla();
        var autor = choice.getSelectedItem();
        Lista resultados = tabla.buscarAutor(autor);
        this.getDatos(resultados);
    }//GEN-LAST:event_sendActionPerformed

    private void send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu v2 = new Menu();

    }//GEN-LAST:event_send1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarAutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice choice;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mostrar;
    private javax.swing.JList<String> panelTitulos;
    private javax.swing.JButton send;
    private javax.swing.JButton send1;
    // End of variables declaration//GEN-END:variables
}
